name:                rezoomer
version:             0.1.0.0
synopsis:            Simple image filter that rezooms regions in a grid defined on the image.
description:         Please see README.md
homepage:            https://github.com/silky/rezoomer#readme
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           Noon van der Silk
category:            Web
extra-source-files:
    - README.md


dependencies:
  - base >= 4.7 && < 5
  - hip >= 1.5.2.0
  - random
  - optparse-generic


executables:
  rezoomer:
    ghc-options:      -Wall
    source-dirs:      app
    main:             Main.hs
